### ISSUE TITLE
Test Harness fails under sklearn 0.23.0+

### ISSUE THREAD

**Issue by mwes** [SD2E/test-harness#1]
Discovered by @georgebzheng 

This looks a an API change that was pushed ~May 12 under sklearn 0.23.0:

```
sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
```

```
>>> from harness.test_harness_class import TestHarness
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/test-harness/harness/test_harness_class.py", line 11, in <module>
    from sklearn.externals import joblib
ImportError: cannot import name 'joblib' from 'sklearn.externals' (/lib/python3.7/site-packages/sklearn/externals/__init__.py
```

**Comment by mwes** [comment]
(Going to file a fix this under GitLab and mirror over)
